// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using player_service.Data;

#nullable disable

namespace player_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130192737_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("player_service.Models.Inventory", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("player_service.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sword",
                            Price = 20
                        },
                        new
                        {
                            Id = 2,
                            Name = "Boots",
                            Price = 5
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shield",
                            Price = 10
                        });
                });

            modelBuilder.Entity("player_service.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Currency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = 100,
                            Experience = 0,
                            Level = 1,
                            Username = "Max"
                        },
                        new
                        {
                            Id = 2,
                            Currency = 100,
                            Experience = 0,
                            Level = 1,
                            Username = "John"
                        },
                        new
                        {
                            Id = 3,
                            Currency = 100,
                            Experience = 0,
                            Level = 1,
                            Username = "Jane"
                        },
                        new
                        {
                            Id = 4,
                            Currency = 100,
                            Experience = 0,
                            Level = 1,
                            Username = "Bob"
                        },
                        new
                        {
                            Id = 5,
                            Currency = 100,
                            Experience = 0,
                            Level = 1,
                            Username = "Alice"
                        });
                });

            modelBuilder.Entity("player_service.Models.Inventory", b =>
                {
                    b.HasOne("player_service.Models.Item", "Item")
                        .WithMany("Inventories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("player_service.Models.Player", "Player")
                        .WithMany("Inventories")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("player_service.Models.Item", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("player_service.Models.Player", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
